import { useEffect, useState, type FormEvent } from 'react';
import { ArrowUpRight, ClipboardCheck, Crosshair, Save } from 'lucide-react';
import { useAuth } from '../auth';
import { EmptyState, StatusBadge } from './Common';
import type { FindingStatus, Inspection, InspectionPatch } from '../types';
import type { EvidenceSelection } from './EvidenceViewer';

export function AssessmentPanel({ inspection, busy, onSave, onSelect, onReview }: { inspection: Inspection; busy: boolean; onSave: (patch: InspectionPatch) => Promise<boolean>; onSelect: (selection: EvidenceSelection) => void; onReview: (decision: string, notes: string) => Promise<boolean> }) {
  const [filter, setFilter] = useState('all');
  const current = inspection.assessments.find(assessment => assessment.id === inspection.current_assessment_id);
  const findings = inspection.findings.filter(finding => filter === 'all' || finding.status === filter);
  return <div className="assessment-layout"><div><div className="assessment-intro"><span className="eyebrow">ASSESSMENT REVIEW</span><h2>Verify each finding against evidence</h2><p>These checks address a limited set of declarations. A potential violation needs human assessment; missing or uncertain evidence needs further review.</p></div>{current ? <><div className="finding-totals">{(['pass', 'needs_review', 'potential_violation', 'not_applicable'] as FindingStatus[]).map(status => <button key={status} className={filter === status ? 'selected' : ''} onClick={() => setFilter(filter === status ? 'all' : status)} aria-pressed={filter === status}><strong>{current.summary[status] || 0}</strong><StatusBadge status={status} /></button>)}</div><div className="section-heading"><h3>{filter === 'all' ? 'All findings' : 'Filtered findings'}</h3>{filter !== 'all' && <button className="text-button" onClick={() => setFilter('all')}>Show all findings</button>}<span className="small muted">Rule set {inspection.rule_version}</span></div><div className="findings-list">{findings.map(finding => <article key={finding.rule_id} className={`finding finding-${finding.status}`}><div className="finding-heading"><span className="rule-code">{finding.rule_id}</span><StatusBadge status={finding.status} /></div><h3>{finding.title}</h3><p>{finding.explanation}</p><div className="finding-links"><div><span>Rule reference</span><a href={finding.source_url} target="_blank" rel="noreferrer">{finding.provision}<ArrowUpRight size={14} /></a></div><div><span>Evidence</span>{finding.evidence_image_id ? <button className="text-button" onClick={() => onSelect({ imageId: finding.evidence_image_id!, box: finding.evidence_box, label: finding.title })}><Crosshair size={15} />{finding.evidence?.panel || 'Open highlighted image'}{finding.evidence?.filename ? ` · ${finding.evidence.filename}` : ''}</button> : <small className="muted">No direct image linked</small>}</div></div></article>)}{!findings.length && <p className="muted">No findings in this category.</p>}</div></> : <EmptyState title="Analysis is required before review.">Upload packaging evidence and run analysis to produce declaration checks. You can record coverage and manual checks now.</EmptyState>}</div><aside className="assessment-sidebar"><ManualChecks inspection={inspection} busy={busy} onSave={onSave} /><ReviewerForm inspection={inspection} busy={busy} onReview={onReview} /></aside></div>;
}

function ManualChecks({ inspection, busy, onSave }: { inspection: Inspection; busy: boolean; onSave: (patch: InspectionPatch) => Promise<boolean> }) {
  const [coverage, setCoverage] = useState(inspection.coverage_confirmed);
  const [checks, setChecks] = useState<Record<string, string>>(inspection.manual_checks);
  useEffect(() => { setCoverage(inspection.coverage_confirmed); setChecks(inspection.manual_checks); }, [inspection.version, inspection.coverage_confirmed, inspection.manual_checks]);
  async function submit(event: FormEvent) { event.preventDefault(); await onSave({ version: inspection.version, coverage_confirmed: coverage, manual_checks: checks }); }
  return <form className="manual-checks" onSubmit={submit}><ClipboardCheck size={24} strokeWidth={1.4} /><h3>The human checks</h3><p>Photographs alone cannot reliably verify every physical packaging requirement.</p><fieldset disabled={busy || inspection.status === 'processing'}><label className="checkbox-row"><input type="checkbox" checked={coverage} onChange={event => setCoverage(event.target.checked)} /><span><strong>All relevant panels are captured.</strong><small>I have checked that the evidence covers the declarations.</small></span></label>{Object.entries({ readability: 'Readability', placement: 'Declaration placement', font_size: 'Type size / dimensions' }).map(([key, label]) => <label key={key}>{label}<select value={checks[key] || 'unassessed'} onChange={event => setChecks(current => ({ ...current, [key]: event.target.value }))}><option value="unassessed">Not yet assessed</option><option value="acceptable">Checked — acceptable</option><option value="concern">Checked — concern</option></select></label>)}<label>Manual review notes<textarea rows={3} value={checks.notes || ''} onChange={event => setChecks(current => ({ ...current, notes: event.target.value }))} placeholder="Record measurements, observations, or missing evidence." maxLength={5000} /></label><button className="button secondary"><Save size={16} />Save manual checks</button></fieldset></form>;
}

function ReviewerForm({ inspection, busy, onReview }: { inspection: Inspection; busy: boolean; onReview: (decision: string, notes: string) => Promise<boolean> }) {
  const { user } = useAuth(); const [decision, setDecision] = useState('follow_up'); const [notes, setNotes] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (await onReview(decision, notes)) setNotes(''); }
  return <section className="reviewer-panel"><span className="eyebrow">REVIEWER DECISION</span><h3>A considered conclusion.</h3>{inspection.review_decision && <div className="existing-review"><StatusBadge status={inspection.review_decision} />{inspection.review_notes && <p>{inspection.review_notes}</p>}</div>}{user?.role === 'reviewer' ? <form onSubmit={submit}><fieldset disabled={busy || !inspection.current_assessment_id || inspection.status === 'processing'}><label>Decision<select value={decision} onChange={event => setDecision(event.target.value)}><option value="follow_up">Follow-up needed</option><option value="accepted">Accept assessment</option></select></label><label>Reviewer notes<textarea value={notes} onChange={event => setNotes(event.target.value)} rows={3} required maxLength={5000} placeholder="Explain your conclusion and any next steps." /></label><p className="small">Acceptance acknowledges the assessment; it does not certify legal compliance. Follow-up keeps unresolved findings explicit.</p><button className="button primary" disabled={!notes.trim()}>Record decision</button></fieldset>{!inspection.current_assessment_id && <p className="small muted">Complete analysis before recording a decision.</p>}</form> : <p className="small muted">A reviewer account can record the decision once an assessment is available.</p>}</section>;
}
