import { useEffect, useState, type FormEvent } from 'react';
import { Save } from 'lucide-react';
import type { Applicability, Inspection, InspectionPatch } from '../types';

export function ContextEditor({ inspection, busy, onSave }: { inspection: Inspection; busy: boolean; onSave: (patch: InspectionPatch) => Promise<boolean> }) {
  const initialApplicability: Applicability = inspection.applicability || { status: inspection.scope_confirmed ? 'applicable' : 'unknown', exemption: 'none', reason: '' };
  const [form, setForm] = useState({ product_name: inspection.product_name, brand: inspection.brand || '', barcode: inspection.barcode || '', origin: inspection.origin, scope_confirmed: inspection.scope_confirmed, notes: inspection.notes || '', applicability: initialApplicability });
  useEffect(() => { setForm({ product_name: inspection.product_name, brand: inspection.brand || '', barcode: inspection.barcode || '', origin: inspection.origin, scope_confirmed: inspection.scope_confirmed, notes: inspection.notes || '', applicability: inspection.applicability || { status: inspection.scope_confirmed ? 'applicable' : 'unknown', exemption: 'none', reason: '' } }); }, [inspection.version, inspection.product_name, inspection.brand, inspection.barcode, inspection.origin, inspection.scope_confirmed, inspection.notes, inspection.applicability]);
  async function submit(event: FormEvent) { event.preventDefault(); await onSave({ version: inspection.version, product_name: form.product_name, brand: form.brand, barcode: form.barcode, origin: form.origin, scope_confirmed: form.applicability.status === 'applicable', applicability: form.applicability, notes: form.notes }); }
  return <details className="context-details"><summary><span>Product context & applicability</span><span>{inspection.origin} · {initialApplicability.status === 'applicable' ? 'applicable' : initialApplicability.status === 'not_applicable' ? 'not applicable' : 'decision required'}</span></summary><form className="context-form" onSubmit={submit}><fieldset disabled={busy || inspection.status === 'processing'}><div className="form-grid"><label>Product name<input required value={form.product_name} onChange={event => setForm(current => ({ ...current, product_name: event.target.value }))} maxLength={200} /></label><label>Brand<input value={form.brand} onChange={event => setForm(current => ({ ...current, brand: event.target.value }))} maxLength={150} /></label><label>Barcode / reference<input value={form.barcode} onChange={event => setForm(current => ({ ...current, barcode: event.target.value }))} maxLength={100} /></label><label>Origin<select value={form.origin} onChange={event => setForm(current => ({ ...current, origin: event.target.value }))}><option value="unknown">Unknown / not verified</option><option value="domestic">Domestic</option><option value="imported">Imported</option></select></label><label>Applicability decision<select value={form.applicability.status} onChange={event => setForm(current => ({ ...current, applicability: { ...current.applicability, status: event.target.value as Applicability['status'] } }))}><option value="unknown">Needs confirmation</option><option value="applicable">Applicable to this product</option><option value="not_applicable">Not applicable</option></select></label><label>Exemption status<select value={form.applicability.exemption} onChange={event => setForm(current => ({ ...current, applicability: { ...current.applicability, exemption: event.target.value as Applicability['exemption'] } }))}><option value="none">No exemption recorded</option><option value="claimed">Exemption claimed — verify</option><option value="confirmed">Exemption confirmed</option></select></label><label className="full-width">Applicability / exemption reason<textarea value={form.applicability.reason} rows={2} onChange={event => setForm(current => ({ ...current, applicability: { ...current.applicability, reason: event.target.value } }))} maxLength={2000} placeholder="Record the product category, exemption basis, or source checked." /></label><label className="full-width">Inspection notes<textarea value={form.notes} rows={2} onChange={event => setForm(current => ({ ...current, notes: event.target.value }))} maxLength={5000} /></label></div><div className="context-guidance"><strong>Applicability is checked before a missing declaration can become a potential violation.</strong><span>Category: {inspection.category}. Unknown or claimed exemptions remain in review.</span></div><button className="button secondary"><Save size={16} />Save context</button></fieldset></form></details>;
}
