import { FileDown, History } from 'lucide-react';
import { EmptyState, formatDate, StatusBadge } from './Common';
import type { Inspection } from '../types';

export function ReportHistory({ inspection }: { inspection: Inspection }) {
  return <section className="reports-panel"><div className="section-heading"><div><span className="eyebrow">REPORT HISTORY</span><h2>Versioned assessment reports</h2></div><History size={26} strokeWidth={1.3} /></div><p className="section-description">Each report uses its saved assessment snapshot, including evidence, rule references, applicability, limitations, and reviewer notes. Later edits produce a new assessment; previous versions stay available.</p>{inspection.assessments.length ? <div className="report-list">{inspection.assessments.map((assessment, index) => <article className="report-row" key={assessment.id}><span className="report-icon"><FileDown size={24} strokeWidth={1.3} /></span><div className="report-info"><div><h3>Assessment {inspection.assessments.length - index}</h3>{assessment.id === inspection.current_assessment_id && <span className="version-tag">Current</span>}</div><p>{formatDate(assessment.created_at, true)} <span>·</span> Version {assessment.assessment_version || assessment.id.slice(0, 8)} <span>·</span> Rule set {assessment.rule_version}</p><small>{assessment.summary.pass} passed · {assessment.summary.needs_review} to verify · {assessment.summary.potential_violation} potential violations <span>·</span> {assessment.evidence_count ?? inspection.images.length} evidence images linked</small></div><div className="report-review">{assessment.review_decision ? <StatusBadge status={assessment.review_decision} /> : <span className="small muted">No reviewer decision</span>}</div><div className="report-downloads"><a className="button secondary small-button" href={`/api/inspections/${inspection.id}/reports/${assessment.id}.pdf`} download><FileDown size={15} />PDF</a><a className="button secondary small-button" href={`/api/inspections/${inspection.id}/reports/${assessment.id}.docx`} download><FileDown size={15} />DOCX</a></div></article>)}</div> : <EmptyState title="No assessment reports yet.">Run an analysis to generate the first versioned report.</EmptyState>}</section>;
}
export function AuditTrail({ inspection }: { inspection: Inspection }) {
  return <section className="audit-panel"><div className="section-heading"><div><span className="eyebrow">TRACE THE DECISIONS</span><h2>Inspection activity</h2></div></div>{inspection.audit.length ? <ol className="audit-list">{inspection.audit.map(event => <li key={event.id}><span className="audit-dot" /><div><h3>{event.action.replaceAll('_', ' ')}</h3><p>{event.detail}</p><small>{event.actor} <b>·</b> {formatDate(event.created_at, true)}</small></div></li>)}</ol> : <EmptyState title="No activity recorded yet.">Saved actions will appear here.</EmptyState>}</section>;
}
